CREATE TABLE IF NOT EXISTS NOBEL_WIN (
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT
);

INSERT INTO NOBEL_WIN(YEAR ,SUBJECT ,WINNER ,COUNTRY ,CATEGORY ) VALUES
(1970,'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
(1971,'PHYSICS','PAUL ','FRANCE','SCIENTIST'),
(1971,'CHEMISTRY','HAMILTON','SWEDEN','LINGUISTS'),
(1972,'LITERRARTURE','BERNARD KELSON','GERMANY','ECONIMISTS'),
(1972,'ECONOMICS','JOSEPH','RUSSIA','ECONIMISTS'),
(1973,'BIOLOGY','PHILIP','USA','PRIME MINISTER'),
(1980,'BIOLOGY','MARTIN','USA','PRESIDENT'),
(1981,'PHYSIOLOGY','HANNAH','SWEDEN','SCIENTIST'),
(1975,'PHYSICS','PETER','CHILE','SCIENTIST');

SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';


